---
title: Configure ontent Delivery Manager
description: Configures Content Delivery Manager not to download applications like Candy Crush Soda and turns off suggested content (tips/tricks/facts/suggestions/ads) for QoL and privacy.
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'ContentDeliveryAllowed'
    data: '0'
    type: REG_DWORD

  - !registryValue: